[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

# [programs.localnet]
# payment_program = "BUujvcx3Ss92E1Rm5AgTGha2mxBM3NefBwWmLYS7mMjN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "../keypairs/payer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
